### ISSUE TITLE
使用源代码默认的测试用例出现如下问题。

### ISSUE THREAD

**Issue by loneyao** [TronGeek/InterfaceTest#2]
操作系统：win7
excel:wps

Traceback (most recent call last):
  File "D:\InterfaceTest-master\LiveApp.py", line 33, in <module>
    logging.basicConfig(format=log_format,filename=log_file,filemode='w',level=logging.DEBUG)
  File "C:\Users\55\AppData\Local\Programs\Python\Python35\lib\logging__init__.py", line 1744, in basicConfig
    h = FileHandler(filename, mode)
  File "C:\Users\55\AppData\Local\Programs\Python\Python35\lib\logging__init__.py", line 1008, in **init**
    StreamHandler.**init**(self, self._open())
  File "C:\Users\55\AppData\Local\Programs\Python\Python35\lib\logging__init__.py", line 1037, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\InterfaceTest-master\log\liveappapi.log'

**Comment by BSTester** [comment]
Sorry，请在D:\InterfaceTest-master\下新建一个log文件夹，代码没有判断此文件夹是否存在。
